<?php
/**
 * Search Form
 *
 * Please do not edit this file. This file is part of the CyberChimps Framework and all modifications
 * should be made in a child theme.
 *
 * @category CyberChimps Framework
 * @package  Framework
 * @since    1.0
 * @author   CyberChimps
 * @license  http://www.opensource.org/licenses/gpl-license.php GPL v3.0 (or later)
 * @link     http://www.cyberchimps.com/
 */

?>

<form method="get" class="navbar-search input-group searchform" action="<?php echo esc_url( home_url( '/' ) ); ?>">
	<input type="text" class="search-query form-control" name="s" placeholder="<?php printf( esc_html__( 'Search', 'compact-one' ) ); ?>&hellip;" />
</form>
<div class="clear"></div>
